packages:
  # Include all of the core configuration
  core: !include esphome-gauhartas204-esp8266.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: vaninanton.esphome-gauhartas204
    version: dev # This will be replaced by the github workflows with the `release` version
  comment: "https://github.com/vaninanton/esphome-gauhartas204"
  includes:
    - uart_read_line_sensor.h

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://vaninanton/esphome-gauhartas204/esphome-gauhartas204-esp8266.yaml@main

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:
