name: CI

on:
  push:
    branches:
      - main
    paths:
      - '*.yaml'
      - 'components/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '*.yaml'
      - 'components/**'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: ESPHome stable
        uses: esphome/build-action@v7
        with:
          yaml-file: esphome-gauhartas204-esp8266.yaml
          version: stable
